marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from utils.routers import DefaultRouter
from django.views.generic import TemplateView
from django.conf.urls import url
from accounts.views import LoginApiView, RegisterApiView

router = DefaultRouter()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include(router.urls)),
    path('api/account/login', LoginApiView.as_view()),
    path('api/account/registration', RegisterApiView.as_view()),
    path('api/accounts/', include('rest_auth.urls')),
    path('api/banners/', include('banners_app.urls')),
    path('api/product/', include('product_app.urls')),
    path('api/profile/', include('accounts.urls')),
    path('api/cart/', include('my_cart.urls')),
    path('api/order/', include('my_orders.urls')),
    path('api/wishlist/', include('my_wishlist.urls')),
    path('api/registrations/', include('rest_auth.registration.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)),]

admin.site.site_title = ""
admin.site.site_header = " Administration"
admin.site.index_title = "Welcome to Admin Portal"

my_cart/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('user/<int:id>', CartView.as_view()),
    path('user/delete/<int:id>', CartView.as_view()),
    path('user', CartView.as_view()),
]

my_orders/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.html import mark_safe
from django.contrib.auth import get_user_model
from product_app.models import *

User = get_user_model()
# Create your models here.


def increment_invoice_number():
    last_invoice = OrderManagement.objects.all().order_by('id').last()
    if not last_invoice:
        return 'RB0001'
    invoice_no = last_invoice.invoice_no
    invoice_int = int(invoice_no.split('RB')[-1])
    new_invoice_int = invoice_int + 1
    new_invoice_no = 'RB000' + str(new_invoice_int)
    return new_invoice_no


class CustomerDetail(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, default='')
    streat_detail = models.TextField(default='', null=True, blank=True)
    city = models.CharField(default='', null=True, blank=True, max_length=100)
    state = models.CharField(default='Delhi', null=True,
                             blank=True, max_length=100)
    phone = models.CharField(blank=True, null=True, max_length=100)
    email = models.EmailField(null=True, blank=True, default='')
    gstn = models.CharField(max_length=150, null=True, blank=True, default='')

    def __str__(self):
        return self.name


class CompanyDetail(models.Model):
    company_name = models.CharField(max_length=100, default='')
    company_gstn = models.CharField(
        max_length=150, null=True, blank=True, default='')
    streat_detail = models.TextField(default='', null=True, blank=True)
    company_city = models.CharField(
        default='', null=True, blank=True, max_length=100)
    company_state = models.CharField(default='Delhi', null=True,
                                     blank=True, max_length=100)
    company_phone = models.CharField(blank=True, null=True, max_length=100)
    company_email = models.EmailField(null=True, blank=True, default='')
    invoice_logo = models.ImageField()

    def __str__(self):
        return self.company_name


class OrderManagement(models.Model):
    GST_PAY = [
        ('yes', 'YES'),
        ('no', 'NO')
    ]
    BIL_PAY = [
        ('paid', 'PAID'),
        ('unpaid', 'UNPAID')
    ]
    DELIVERY_STATUS = [
        ('Pending', 'Pending'),
        ('Out for delivery', 'Out for delivery'),
        ('Delivered', 'Delivered')
    ]
    PAYMENT_METHOD = [
        ('Cash On Delivery', 'Cash On Delivery')
    ]

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    CompanyDetail = models.ForeignKey(CompanyDetail, null=True, blank=True, on_delete=models.CASCADE)
    product_detail = models.ManyToManyField(Product, blank=True)
    additional_notes = models.TextField(
        max_length=1500, null=True, blank=True, default='')
    gst_payable = models.CharField(
        choices=GST_PAY, default='no', max_length=100)
    invoice_no = models.CharField(
        max_length=500, default=increment_invoice_number, null=True, blank=True)
    invoice_date = models.DateField(auto_now=True)
    billing_date = models.DateField(auto_now=True)
    delivery_date = models.DateField(auto_now=True)
    payment_status = models.CharField(
        choices=BIL_PAY, default='unpaid', max_length=100)
    delivery_status = models.CharField(choices=DELIVERY_STATUS, max_length=100, default='Pending')
    payment_method = models.CharField(choices=PAYMENT_METHOD, max_length=100, default='Cash On Delivery')
    generate_invoice = models.CharField(
        max_length=300, null=True, blank=True, default='')

    def invoice_generate(self):
        return mark_safe('<a target="_blank" href="%s">%s</a>' % (self.generate_invoice, 'Generate Invoice'))
    invoice_generate.allow_tags = True


@receiver(post_save, sender=OrderManagement)
def my_handler(sender, instance, **kwargs):
    invoice_url = f'/order/admin/print/invoice/{instance.id}'
    print(invoice_url)
    order = OrderManagement.objects.filter(
        id=instance.id).update(generate_invoice=invoice_url)
    print(order)

templates/files/create_update_videocall_service_account.html
{% extends 'uplevel_admin/base.html' %}
{% load static %}

{% block title_content %}
  {% if instruction %}
    Update Video Call Service Account: {{ video_call_service_account }}
  {% else %}
    Create Video Call Service Account
  {% endif %}
{% endblock title_content %}

{% block breadcrumb_content %}
  {{ block.super }}

  <li class="breadcrumb-item"><a href="{% url 'video_call:video_call_service_accounts' %}">video_call_service_accounts</a>
  </li>
  <li class="breadcrumb-item active" aria-current="page">
    {% if video_call_service_account %}
      Update Video Call Service Account
    {% else %}
      Create Video Call Service Account
    {% endif %}
  </li>
{% endblock breadcrumb_content %}

{% block heading_content %}
  {% if video_call_service_account %}
    Update Video Call Service Account
  {% else %}
    Create Video Call Service Account
  {% endif %}
{% endblock heading_content %}

{% block content_inside_container_div_in_content_body_div %}

  <div class="card mt-4">

    <form id="id_form_video_call_service_account_details">

      <div class="card-body pd-20 pd-sm-30">
        <div class="row justify-content-center">
          <div class="col-lg-9 col-xl-7">

            <div class="form-group">
              <label class="tx-11 tx-uppercase tx-medium tx-spacing-1 tx-color-03">Name<span
                  class="tx-danger">*</span></label>
              <input id="id_name" type="text" name="name" class="form-control" autocomplete="off" placeholder="Enter Name"
                value="{% if video_call_service_account %}{{ video_call_service_account.name }}{% endif %}" required="">
              <ul id="id_name_errors" class="custom-errors-list"></ul>
            </div>

            <div class="form-group">
              <label class="tx-11 tx-uppercase tx-medium tx-spacing-1 tx-color-03">Email<span
                  class="tx-danger">*</span></label>
              <input id="id_email" type="email" name="email" class="form-control" autocomplete="off"
                placeholder="Enter email"
                value="{% if video_call_service_account %}{{ video_call_service_account.email }}{% endif %}" required="">
              <ul id="id_email_errors" class="custom-errors-list"></ul>
            </div>

            <div class="row">

              <div class="col-md-6">
                <div class="form-group">
                  <label class="tx-11 tx-uppercase tx-medium tx-spacing-1 tx-color-03">
                    Account Type<span class="tx-danger">*</span>
                  </label>
                  <select id="id_video_call_service" name="video_call_service" style="width: 100%;"
                    data-parsley-errors-container="#id_account_type_errors">
                    <option value="ZOOM">Zoom</option>
                  </select>
                  <div id="id_video_call_service_errors"></div>
                  <ul id="id_video_call_service_errors" class="custom-errors-list"></ul>
                </div>
              </div>

              <div class="col-md-6">
                <div class="form-group">
                  <label class="tx-uppercase tx-11 tx-medium tx-spacing-1 tx-color-03">External Account ID<span
                      class="tx-danger">*</span></label>
                  <input id="id_external_account_id" type="text" name="external_account_id" class="form-control"
                    autocomplete="off" placeholder="Enter Account ID"
                    value="{% if video_call_service_account %}{{ video_call_service_account.external_account_id }}{% endif %}"
                    required="">
                  <ul id="id_external_account_id_errors" class="custom-errors-list"></ul>
                </div>
              </div>

            </div>

            <div class="form-group mb-0">
              <label class="tx-uppercase tx-11 tx-medium tx-spacing-1 tx-color-03">Cohort</label>
              <select id="id_cohort" name="cohort" style="width: 100%;"
                data-parsley-errors-container="#id_parsley_cohort_errors">
                <option></option>
                {% for cohort in all_cohorts %}
                <option value="{{ cohort.id }}" {% if video_call_service_account.cohort == cohort %} selected {% endif %}>
                  {{ cohort }}
                </option>
                {% endfor %}

              </select>
              <div id="id_parsley_cohort_errors"></div>
              <ul id="id_cohort_errors" class="custom-errors-list"></ul>
            </div>
            <div class="custom-errors-list" id="id_error_list"></div>
          </div>

        </div>
      </div>
      <div class="card-footer pd-y-15 pd-x-25">
        <div class="row justify-content-center">
          <div class="col-lg-9 col-xl-7">
            <div class=" d-flex flex-column flex-sm-row">
              <div class="d-flex d-sm-block">
                <button id="id_btn_video_call_service_account_save" type="submit"
                  class="btn btn-sm btn-success btn-uppercase mr-2 flex-fill pd-x-40">
                  Save</button>
                <a href="{% url 'video_call:video_call_service_accounts' %}"
                  class="btn btn-sm btn-light btn-uppercase flex-fill pd-x-30">Cancel</a>
              </div>

              {% if video_call_service_account %}
                <button id="id_btn_delete_service_account" type="button" class="btn btn-link btn-uppercase mt-3 mt-sm-0 text-danger ml-auto mr-auto mr-sm-0">
                  <i data-feather="trash" class="mr-1"></i> Delete
                </button>
              {% endif %}

            </div>
          </div>
        </div>
      </div>

    </form>
    
  </div>

  <div id="id_modal_service_account_delete_not_possible" class="modal modal-invitation-exp fade" id="id_modal_select_invitation_expiration_date" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered" style="width: 260px" role="document">
      <div class="modal-content">
        <div class="modal-body px-0 py-2">
          <h5>Service Account is Being Used. It can not be deleted</h5>
        </div>
        <div class="modal-footer pd-x-20 pd-y-15">
          <button type="button" class="btn btn-sm btn-white" data-dismiss="modal">Okay</button>
        </div>
      </div>
    </div>
  </div>

  {% if video_call_service_account %}
    <div class="row">
      <div class="col">
        <ul class="info-row mg-b-0 mg-t-20 tx-10 tx-medium tx-spacing-1 tx-color-03 tx-uppercase tx-sans">
          <li>
            Created at: {{ video_call_service_account.created_at }}
          </li>
          <li>
            Created by:
            {% if video_call_service_account.created_by %}
             {{ video_call_service_account.created_by }}
            {% else %}
             UNKNOWN
            {% endif %}
          </li>
          <li>
            Last updated at:
            <span id="id_last_updated_at">
              {{ video_call_service_account.last_updated_at }}
            </span>
          </li>
          <li>
            Last updated by:
            <span id="id_last_updated_by">
              {% if video_call_service_account.last_updated_by %}
               {{ video_call_service_account.last_updated_by }}
              {% else %}
               UNKNOWN
              {% endif %}
            </span>
          </li>
        </ul>
      </div>
    </div>
  {% endif %}

{% endblock content_inside_container_div_in_content_body_div %}


{% block content_just_after_common_scripts %}
  
  <script>
    var csrfmiddlewaretoken = "{{ csrf_token }}";
    var listURL = "{% url 'video_call:video_call_service_accounts' %}";
    var createURL = "{% url 'video_call:service_account-list' %}";
    var updateURL = '';

    var id = null;
    {% if video_call_service_account %}
      var updateURL = "{% url 'video_call:service_account-detail' video_call_service_account.id %}"
      var id = "{{ video_call_service_account.id }}";
    {% endif %}

  </script>
  <script src="{% static 'uplevel_admin/video_call/create_update_service_account.js' %}"></script>
{% endblock content_just_after_common_scripts %}

templates/files/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  </head>
  <body>
    <script>
    // similar behavior as an HTTP redirect
    window.location.replace("html/index.html");
    </script>
  </body>
</html>

templates/files/videocall_service_account.html
{% extends 'uplevel_admin/base.html' %}

{% load static %}

{% block title_content %}
  Video Call Service Accounts
{% endblock title_content %}

{% block breadcrumb_content %}
  {{ block.super }}
  <li class="breadcrumb-item active" aria-current="page">System Setup</li>
{% endblock breadcrumb_content %}

{% block heading_content %}
  Video Call Service Accounts
{% endblock heading_content %}

{% block actions_content %}
  <div class="mt-3 text-right">

    <a href="{% url 'video_call:create_video_call_service_account' %}"
       class="btn btn-sm pd-x-15 btn-outline-primary btn-uppercase mg-l-5">
      <i class="fa fa-plus mg-r-3"></i>
      Add new Account
    </a>
  </div>
{% endblock actions_content %}

{% block content_inside_container_div_in_content_body_div %}
  <div class="df-example demo-table">
    <table id="id_tbl_service_accounts" class="display responsive" style="width:100%">
    </table>
  </div>
{% endblock content_inside_container_div_in_content_body_div %}

{% block content_just_after_common_scripts %}
  <script>
    $(function () {
      //Select "active" css in left menu bar
      $("#id_system_setup_category_in_left_nav_bar").addClass("active show");
      $("#id_jobs_in_left_nav_bar").addClass("active");
    });
    var csrfmiddlewaretoken = "{{ csrf_token }}";

    var getUrl = "{% url 'video_call:service_account-list' %}";
    var updateUrl = "{% url 'video_call:update_video_call_service_account' id=12345 %}";

    function getLinkForUpdating(id, name) {
      var url = updateUrl.replace(/12345/, id);
      return "<h6 class='m-0'><a class='link-01' href=" + url + ">" + name + "</a></h6>";
    }

  </script>
  <script src="{% static 'uplevel_admin/video_call/get_service_account.js' %}"></script>
{% endblock content_just_after_common_scripts %}